### ISSUE TITLE
Is it still working?

### ISSUE THREAD

**Issue by crbertoldo** [scrapehero/alibaba-scraper#1]
My test with 'headphones' has returned no result and no error is being raised in log, then I think the page structure was modified.

**Comment by doricardo** [comment]
I don't think so. I thing the class's has changed

**Comment by AzamatShaimerden** [comment]
with little adjustments its scrapes but not yelding anything.

**Comment by scrapehero-code** [comment]
Updated scraper to latest alibaba.com structure and added pagination in search results.
